// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Repository;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260504125447_AddedHistoryForPlantAndDiseaseScans")]
    partial class AddedHistoryForPlantAndDiseaseScans
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.DiseaseID.Disease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("QueryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QueryId");

                    b.ToTable("Diseases");
                });

            modelBuilder.Entity("Domain.Models.DiseaseID.DiseaseIDquery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("Images")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("IncludeRelatedImages")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<bool>("NoReject")
                        .HasColumnType("boolean");

                    b.Property<int>("NumResult")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("Organs")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("DiseaseIDquery");
                });

            modelBuilder.Entity("Domain.Models.DiseaseID.DiseaseResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("DiseaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("DiseaseId");

                    b.ToTable("DiseaseResult");
                });

            modelBuilder.Entity("Domain.Models.History.DiseaseScanHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ResultText")
                        .HasColumnType("text");

                    b.Property<DateTime>("ScannedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DiseaseScanHistories");
                });

            modelBuilder.Entity("Domain.Models.History.PlantScanHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ResultText")
                        .HasColumnType("text");

                    b.Property<DateTime>("ScannedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PlantScanHistories");
                });

            modelBuilder.Entity("Domain.Models.Identity.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirebaseUserId")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Domain.Models.PlantID.Plant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BestMatch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreferedReferential")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("QueryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QueryId");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("Domain.Models.PlantID.PlantIdentificationQuery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Detailed")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<string[]>("Images")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("IncludeRelatedImages")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("NoReject")
                        .HasColumnType("boolean");

                    b.Property<int>("NumResult")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("Organs")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PlantIdentificationQuery");
                });

            modelBuilder.Entity("Domain.Models.PlantID.PlantResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PlantId")
                        .HasColumnType("uuid");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("PlantResult");
                });

            modelBuilder.Entity("Domain.Models.PlantID.PredictedOrgan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Organ")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PlantId")
                        .HasColumnType("uuid");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("PredictedOrgan");
                });

            modelBuilder.Entity("Domain.Models.PlantID.Species", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("CommonNames")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GenusId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScientificNameAuthorship")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScientificNameWithoutAuthor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("GenusId");

                    b.ToTable("Species");
                });

            modelBuilder.Entity("Domain.Models.PlantID.Taxon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScientificNameAuthorship")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScientificNameWithoutAuthor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Taxon");
                });

            modelBuilder.Entity("Domain.Models.Plants.Fruit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string[]>("AgroecologicalZones")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("CommonNames")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string[]>("CulinaryUses")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Genus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HarvestSeason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasSeeds")
                        .HasColumnType("boolean");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NutritionalInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginRegion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TasteProfile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Fruits", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgroecologicalZones = new[] { "Temperate" },
                            CommonNames = new[] { "Apple", "Red Apple" },
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CulinaryUses = new[] { "Raw", "Juice", "Pie" },
                            Description = "A sweet red fruit",
                            Family = "Rosaceae",
                            Genus = "Malus",
                            HarvestSeason = "Autumn",
                            HasSeeds = true,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/1/15/Red_Apple.jpg",
                            Name = "Apple",
                            NutritionalInfo = "Rich in fiber and vitamin C",
                            OriginRegion = "Central Asia",
                            ScientificName = "Malus domestica",
                            TasteProfile = "Sweet"
                        },
                        new
                        {
                            Id = 2,
                            AgroecologicalZones = new[] { "Tropical" },
                            CommonNames = new[] { "Banana" },
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CulinaryUses = new[] { "Raw", "Smoothies", "Baking" },
                            Description = "A tropical yellow fruit",
                            Family = "Musaceae",
                            Genus = "Musa",
                            HarvestSeason = "Year-round",
                            HasSeeds = false,
                            ImageUrl = "",
                            Name = "Banana",
                            NutritionalInfo = "Rich in potassium and vitamin B6",
                            OriginRegion = "Southeast Asia",
                            ScientificName = "Musa acuminata",
                            TasteProfile = "Sweet"
                        },
                        new
                        {
                            Id = 3,
                            AgroecologicalZones = new[] { "Temperate" },
                            CommonNames = new[] { "Strawberry" },
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CulinaryUses = new[] { "Raw", "Jam", "Desserts" },
                            Description = "A small red sweet fruit",
                            Family = "Rosaceae",
                            Genus = "Fragaria",
                            HarvestSeason = "Spring",
                            HasSeeds = true,
                            ImageUrl = "",
                            Name = "Strawberry",
                            NutritionalInfo = "Rich in vitamin C and antioxidants",
                            OriginRegion = "Europe and Americas",
                            ScientificName = "Fragaria ananassa",
                            TasteProfile = "Sweet and Sour"
                        },
                        new
                        {
                            Id = 4,
                            AgroecologicalZones = new[] { "Tropical", "Subtropical" },
                            CommonNames = new[] { "Mango" },
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CulinaryUses = new[] { "Raw", "Juice", "Desserts" },
                            Description = "A tropical stone fruit",
                            Family = "Anacardiaceae",
                            Genus = "Mangifera",
                            HarvestSeason = "Summer",
                            HasSeeds = true,
                            ImageUrl = "",
                            Name = "Mango",
                            NutritionalInfo = "Rich in vitamin A and C",
                            OriginRegion = "South Asia",
                            ScientificName = "Mangifera indica",
                            TasteProfile = "Sweet"
                        });
                });

            modelBuilder.Entity("Domain.Models.Plants.Vegetable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string[]>("AgroecologicalZones")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("CommonNames")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string[]>("CulinaryUses")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EdiblePart")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Genus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HarvestSeason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsLeafy")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NutritionalInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginRegion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Vegetables", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgroecologicalZones = new[] { "Temperate" },
                            CommonNames = new[] { "Carrot" },
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CulinaryUses = new[] { "Raw", "Cooked", "Soup" },
                            Description = "An orange root vegetable",
                            EdiblePart = "Root",
                            Family = "Apiaceae",
                            Genus = "Daucus",
                            HarvestSeason = "Autumn",
                            ImageUrl = "",
                            IsLeafy = false,
                            Name = "Carrot",
                            NutritionalInfo = "Rich in beta-carotene and vitamin A",
                            OriginRegion = "Central Asia",
                            ScientificName = "Daucus carota"
                        },
                        new
                        {
                            Id = 2,
                            AgroecologicalZones = new[] { "Temperate" },
                            CommonNames = new[] { "Spinach" },
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CulinaryUses = new[] { "Raw", "Cooked", "Salads" },
                            Description = "A leafy green vegetable",
                            EdiblePart = "Leaf",
                            Family = "Amaranthaceae",
                            Genus = "Spinacia",
                            HarvestSeason = "Spring",
                            ImageUrl = "",
                            IsLeafy = true,
                            Name = "Spinach",
                            NutritionalInfo = "Rich in iron and vitamin K",
                            OriginRegion = "Central and Western Asia",
                            ScientificName = "Spinacia oleracea"
                        },
                        new
                        {
                            Id = 3,
                            AgroecologicalZones = new[] { "Temperate", "Tropical" },
                            CommonNames = new[] { "Tomato" },
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CulinaryUses = new[] { "Raw", "Sauce", "Salads" },
                            Description = "A red fruit often used as a vegetable",
                            EdiblePart = "Fruit",
                            Family = "Solanaceae",
                            Genus = "Solanum",
                            HarvestSeason = "Summer",
                            ImageUrl = "",
                            IsLeafy = false,
                            Name = "Tomato",
                            NutritionalInfo = "Rich in lycopene and vitamin C",
                            OriginRegion = "South America",
                            ScientificName = "Solanum lycopersicum"
                        },
                        new
                        {
                            Id = 4,
                            AgroecologicalZones = new[] { "Temperate" },
                            CommonNames = new[] { "Broccoli" },
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CulinaryUses = new[] { "Cooked", "Steamed", "Stir-fry" },
                            Description = "A green cruciferous vegetable",
                            EdiblePart = "Flower head",
                            Family = "Brassicaceae",
                            Genus = "Brassica",
                            HarvestSeason = "Autumn",
                            ImageUrl = "",
                            IsLeafy = false,
                            Name = "Broccoli",
                            NutritionalInfo = "Rich in vitamin C and K",
                            OriginRegion = "Mediterranean",
                            ScientificName = "Brassica oleracea"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Models.DiseaseID.Disease", b =>
                {
                    b.HasOne("Domain.Models.DiseaseID.DiseaseIDquery", "Query")
                        .WithMany()
                        .HasForeignKey("QueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Query");
                });

            modelBuilder.Entity("Domain.Models.DiseaseID.DiseaseResult", b =>
                {
                    b.HasOne("Domain.Models.DiseaseID.Disease", null)
                        .WithMany("Results")
                        .HasForeignKey("DiseaseId");
                });

            modelBuilder.Entity("Domain.Models.History.DiseaseScanHistory", b =>
                {
                    b.HasOne("Domain.Models.Identity.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.History.PlantScanHistory", b =>
                {
                    b.HasOne("Domain.Models.Identity.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.PlantID.Plant", b =>
                {
                    b.HasOne("Domain.Models.PlantID.PlantIdentificationQuery", "Query")
                        .WithMany()
                        .HasForeignKey("QueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Query");
                });

            modelBuilder.Entity("Domain.Models.PlantID.PlantResult", b =>
                {
                    b.HasOne("Domain.Models.PlantID.Plant", null)
                        .WithMany("Results")
                        .HasForeignKey("PlantId");

                    b.HasOne("Domain.Models.PlantID.Species", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("Domain.Models.PlantID.PredictedOrgan", b =>
                {
                    b.HasOne("Domain.Models.PlantID.Plant", null)
                        .WithMany("PredictedOrgans")
                        .HasForeignKey("PlantId");
                });

            modelBuilder.Entity("Domain.Models.PlantID.Species", b =>
                {
                    b.HasOne("Domain.Models.PlantID.Taxon", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.PlantID.Taxon", "Genus")
                        .WithMany()
                        .HasForeignKey("GenusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");

                    b.Navigation("Genus");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Domain.Models.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Domain.Models.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Domain.Models.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.DiseaseID.Disease", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("Domain.Models.PlantID.Plant", b =>
                {
                    b.Navigation("PredictedOrgans");

                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
